### ISSUE TITLE
Can't install  this package for Laravel 5.1

### ISSUE THREAD

**Issue by geniuslinchao** [Indatus/laravel-PSRedis#2]
My Laravel version is 5.1. I install PSRedis step by step, but not work, the Error is:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for indatus/laravel-ps-redis dev-master -> satisfiable by indatus/laravel-ps-redis[dev-master].
    - indatus/laravel-ps-redis dev-master requires sparkcentral/psredis dev-master -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Please help and thank you.

**Comment by wins1908** [comment]
+1

**Comment by bkuhl** [comment]
L5 compatibility is here - see https://github.com/Indatus/laravel-PSRedis/releases/tag/v1.2
