### ISSUE TITLE
laravel 5 update

### ISSUE THREAD

**Issue by schandrasekhar** [Indatus/laravel-PSRedis#3]
Hi 
Can u please update the dependencies to laravel 5 (or) I can sent a pull request. Please let me know what is convenient for u.

**Comment by bkuhl** [comment]
A pull request would be welcomed, thanks!

**Comment by bkuhl** [comment]
L5 compatibility is here - see https://github.com/Indatus/laravel-PSRedis/releases/tag/v1.2
